apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: go-app
  name: helm-deploy-role
rules:
- apiGroups: [""]
  resources: ["secrets", "services", "pods", "deployments", "configmaps", "services/finalizers"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", replicasets]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-deploy-role-binding
  namespace: go-app
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: helm-deploy-role
  apiGroup: rbac.authorization.k8s.io


