apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-locally
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "run"
        - "tekton-triggers-built-me"
        - "--image"
        - "$(params.IMAGE)"
        - "--env=PORT=8080"