replicaCount: 1

namespace: go-app

image:
  repository: fsubasi/tekton
  pullPolicy: IfNotPresent
  tag: "main-3537be4e-1712528660"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}