apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: go
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080