apiVersion: v1
kind: Service
metadata:
  name: go
  namespace: go-app
  labels:
    app: go
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go
  type: NodePort